export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_PRICES = 'GET_PRODUCT_PRICES';
export const RESET_PRODUCT_PRICES = 'RESET_PRODUCT_PRICES';
export const ERROR_OCCURED = 'ERROR_OCCURED';
export const FETCHING_COMPONENTS = 'FETCHING_COMPONENTS';



